import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { ClerkProvider } from "@clerk/nextjs";

import TopNav from "./_components/top-nav";

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal subscriber to Theo on Youtube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex flex-col gap-4 bg-black text-white">
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
