name: CI

on: [push, pull_request]

env:
  POSTGRES_URL: "placeholder text"
  POSTGRES_PRISMA_URL: "placeholder text"
  POSTGRES_URL_NO_SSL: "placeholder text"
  POSTGRES_URL_NON_POOLING: "placeholder text"
  POSTGRES_USER: "placeholder text"
  POSTGRES_HOST: "placeholder text"
  POSTGRES_PASSWORD: "placeholder text"
  POSTGRES_DATABASE: "placeholder text"

  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "placeholder text"
  CLERK_SECRET_KEY: "placeholder text"

  KINDE_CLIENT_ID: "placeholder text"
  KINDE_CLIENT_SECRET: "placeholder text"
  KINDE_ISSUER_URL: "placeholder text"
  KINDE_SITE_URL: "placeholder text"
  KINDE_POST_LOGOUT_REDIRECT_URL: "placeholder text"
  KINDE_POST_LOGIN_REDIRECT_URL: "placeholder text"

  UPLOADTHING_SECRET: "placeholder text"
  UPLOADTHING_APP_ID: "placeholder text"

  SENTRY_AUTH_TOKEN: "placeholder text"

  NEXT_PUBLIC_POSTHOG_KEY: "placeholder text"
  NEXT_PUBLIC_POSTHOG_HOST: "placeholder text"

  UPSTASH_REDIS_REST_URL: "placeholder text"
  UPSTASH_REDIS_REST_TOKEN: "placeholder text"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
